# test_1 = Ilohv::Directory.create!(name: 'Test 1')
# child_1 = test_1.directories.create!(name: 'Child 1')
# child_1.files.create!(name: 'File 1')
# child_1.files.create!(name: 'File 2')
# child_2 = test_1.directories.create!(name: 'Child 2')
# test_2 = Ilohv::Directory.create!(name: 'Test 2')
# test_2.files.create!(name: 'File 3')
# test_2.files.create!(name: 'File 4')

test_1 = Ilohv::Directory.create!(name: 'Test 1')
child_1 = Ilohv::Directory.create!(parent: test_1, name: 'Child 1')
Ilohv::File.create!(parent: child_1, name: 'File 1')
Ilohv::File.create!(parent: child_1, name: 'File 2')
child_2 = Ilohv::Directory.create!(parent: test_1, name: 'Child 2')
test_2 = Ilohv::Directory.create!(name: 'Test 2')
Ilohv::File.create!(parent: test_2, name: 'File 3')
Ilohv::File.create!(parent: test_2, name: 'File 4')
