seeds = Rails.root.join('db/seeds')

programming = Ilohv::Directory.create!(name: 'Programming')
fun = Ilohv::Directory.create!(parent: programming, name: 'Fun')
Ilohv::File.create!(parent: fun, name: 'One Does Not Simpy Turbolinks', file: seeds.join('one-does-not-simply-turbolinks.jpg').open)
Ilohv::File.create!(parent: fun, name: 'Unit Test All The Things', file: seeds.join('unit-test.jpg').open)
tutorials = Ilohv::Directory.create!(parent: programming, name: 'Tutorials')
university = Ilohv::Directory.create!(name: 'Workflow Management')
Ilohv::File.create!(parent: university, name: 'Workflow Resource Patterns: Identification, Representation and Tool Support', file: seeds.join('ResourcePatternsCAiSE.pdf').open)
Ilohv::File.create!(parent: university, name: 'Exception Handling Patterns in Process-Aware Information Systems', file: seeds.join('BPM-06-04.pdf').open)
